# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='bodyText',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='body'),
            preserve_default=False,
        ),
    ]
